# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 976ff01fd72fc5a8c1bd5be4fc8e2a2d11a19ef8473298f124c40eaa0e8b0f7f1c2d4eeb98e38f7b22689add103311f66cc5a4287b14db79c5bd3b322d5428e3

test:
  secret_key_base: 5f5020d6a065c8743dda28dadc014d441d424fd752e7ac7047c61998c7a998c7489728c5a967df942baf96c9bbad1f7da180732d14a8212ed76eb310d2ad976b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
